pipeline {
    agent { label 'master' }
    stages {
         stage('Checkout source') {
        steps {
            git branch: 'master',
                credentialsId: 'github_1',
                url: 'https://github.com/johndpotts/simple-java-maven-app.git'

            bat "echo 'hello!'"
        }
    }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
